language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

node_js: "7"

jobs:
  include:
    - stage: Linters
      script: grunt lint
      install:
        - npm install
        - pip install .[tools]
      if:
        python == "3.8"

    - stage: Unit tests
      script:
        - grunt tests:unit
      install:
        - npm install
        - pip install .[tests]
      
    - stage: Test coverage
      script:
        - grunt tests:coverage
      install:
        - npm install
        - pip install .[tests]
      before_script:
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
      after_success:
        - bash <(curl -Ls https://coverage.codacy.com/get.sh)
      env:
        secure: mAhsb7WaRodlGOwqdDosgo2vJfhQRwbCY+rd3yBQgVlKq3IbRQJ+Le3KcgmlwM8eUrIsIoOEijRBsIl52gR3+BUalpjv0bYxhxx8lm4IG9o1su6E3qpadmfi8BNiNNZXsDxyqAXQvA6LgG8U4m9WR4Qf2QuIfuSzXRMCZEr9kJAD9yc3GnMHXxGFv/5aoc1rmrf9VVuTpgbd9SloRDlVAmmbAdP9YfIzTLq18nUz3p/1H246PCByURSONeE7GTvIdbW7Imgxs4AbyXPs0eGNvHH8SlYL4Nq1tNFjsCzcImHXWp1FLSAM/HYMzEJdTIgzDGNRkFNIvPnIJlc0cx4bhrnLrPC4LTBL8sU1NyTtZM+2VYnJcQFSu9WV9kmZZeoHVuWkd1RqfR28Q5MAXFkavYufvKfm8Gk65PedcbbcAcnOm1Sdp4QUkQZTmHfceW9qYtAh5xh248mv2kqvpS9YxTBQNvXqVyD/zttuUYwh8OH4cYm9Y1DW7mPXzHe+ZggYkRA5GHc18GKNMFHOCqvGUH5HNKOXXaQwB89hb+wLCCS858HfjnY3kul1O/mm0zrKgfB6KShLU6gh0Uys8uFIPSryhNGev+7wY4Vm4X0BQE545JgMGPe+yAYJgE9ybtiTHDICc9bAv1UxyEC4J0Ej/QsESvYLA2cgz0v28+ZrmuI=
      if:
        python == "3.8"

    - stage: Docs
      script: grunt docs:build
      install:
        - npm install
        - pip install -r docs/requirements.txt
      if:
        python == "3.8"

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: joellefkowitz
  password:
    secure: fbaBrbBl6mJf54iV2LR/wskFZRGn1ftlgt+BCCGsdF2eDrASnQaszS/IM4PXd4bsUalAPcxcbGC0lEAqiDgZneKlSYvHps1oy6ypymq7JLHKW/iQ3bBeXvT2QEaUgg5LqjX2CIlhSgiY2mVa6gQt1BwlutJatM3sJ6yvBQu+3vVWpwWohfTqjPmt1FdR9WWz5/sviDFyHYnGSRmgQUkcyfnKHZ4/UtEiLynVC1RVNzb+aAOCp2M2lW+A2SBiKMISzbkvgL/pO9f8ceHInUhY+oZJ/wzMa1hyF+Dlo7ut3LywFNrFdheP5r/1lTusR5UYXKncsiCLCyRujal8hOAnUaHkP+XGm+QLULKOGG2qkxmasO7lRXSbYgQGEGoKQNsiwjqJN3AbofIL1FIw/2IYFia/bkvhZCyBLUAHoCJ0BgNF/kvYBDzBDR2b6r8GjG2OREL+tkgAAsHauRgYKfkP738Qqj8UEnQ+Xrtnm+zOw86AuYD4xx3DHS2qAzsnhEs4nVp6WvLSB4PqOzzLZmG73zQZgKTTGIs7kgtnIZBR+3gIQCFIUAaeV9rzNmED0eKt8qLtC4gXFLx5aqzM2hOnuuKII+Ueiz8ZPbjFXrE7VmpCr0KfJaxu4UcqgSjJY5OI9f3EGJsJIC7O1fkrNCNPH0UUTZM0fM9OlxUNPs8qp1I=
  on:
    tags: true
