language: python
python: 3.8

before_install:
  - pip install .
  - nvm install 14
  - npm install
  - npm install -g grunt-cli

cache:
  - pip
  - npm

aliases:
  codacy_report: &codacy_report
    after_success: python-codacy-coverage -r coverage.xml
  
  codacy_secure: &codacy_secure
    env:
      secure: >-
        azswN6AXnY6C5WWuXK5z+v6zFbt5CLwY9Lbqt0w0kP4rxLPhnQB7iJQKvSacDiNt4DzGj/R
        HUYw6bO5pO7xb30ptzbBNd+W+fbMk4uLtzW24SEuVUSc7xDZbglXM8qvawmc/yA+bzpD6Rr
        ZHVwcb5/4efrllgHqah6WjShMaZzJVznVR+/eLfD+jU2R+52xK3mYYBCKsxdDZKi+oUY8lV
        0Zs1xdcalHMAqb3mKWZ8zb2dBnsLkc13fbTo4QYeV2j9YmVDtPUZ4L+cj/nCM1RSFt2gYoq
        shFMcplM2/+H+GreEpCrmbvi2mskZgl8hehIcr8w1jym3AcpCGRP9CvJ6Bazo6xvEw3Odrt
        Azw/z/k4aHnmjiqGphAJ6S69kKHrKcPddAx15Is6l9/uSxBxlMktAyv8KLOX1lUmOKx/Itt
        dWjXQhzbZpvdiTAOTCbfzIggkws2kvCUjZ/HqE99/MUHt2QbWjSpqwB0nuM7bMm9RP1mHcI
        UAu6Drrq24fFtlx/f/hGIINHcE2gQJrRETVMOPqDJNxnhAIyEh4y69M3XtrqWZcNZ5vkQI0
        Rn6jwsyMaUkC2SuwBoolovWRpmi/bMl3QkL7hH9gq+1dNevJZVuSeP75buxwLaJqgfp0yaI
        xISoG0Yj5H0B9AqfZV/zai5QoMq8RVFIQinZ6N15JPb8=

  install_pandoc: &install_pandoc
    addons:
      apt:
        packages:
          - pandoc

  pypi_secure: &pypi_secure
    password:
      secure: >-
        JVlzD2HdIFVcp/9pHQFlpX8DlLE71c1VqEq4wbeJzK9UI+kqK0sTGhG8jqd2yNEuQIWf8hp
        pbMY6WUCYAH7HY2wf1cjRPknWw/aB5zQB3+aFe4s0oEHNzkWRacBTyG/yENJEyh0QGWJxMc
        J21xV1v5s5u4XuV1PHvCqJCl4MZ/1JD7CUWvrdmoHIsVng3Nyjjng8yfuwWaCvkewT/0lml
        ISF7EMXhxu2j1YNnQRTs3SETjQkpovpdj67TJy/SNb8DJ8uV/2A6bQDxtd3C4YdpbkvvefT
        mLMfcbM2pGrpPi8P69Y0ts9H9i79c+OP1mNxOSpSbIWGGPHIuI1TSD5bddiGUDQpFuIZ5gQ
        ghoBGsJ5+S9suoMg0QyhF1wYFp0rlmgnMspBLJIO0nU3eRSjtilQQAc5mT9RmuB1y/iOFHn
        EUKgnFh4qE0Zzec3AyvphUzQI2IY9533e5Y07trXI9k5InGd4jWXpyaC1PJizToYCtOsjcJ
        W7yZtEuZ8cPlR9XqROo4Edv7P1PWrqfGBtgQ1DA+3FCpn0BSb2SoNAZXLkZjicD82Bbc8IN
        FabDkDIWW5Sn8EOHBO1/CA8f8eoa/qZFhUPodGz83vO02n7aBHuiR8nacV/JwS938feM4R9
        5zT7hOwp3rqfVoTW0zMsaewpcVOnQr5MW3WqEeFXdXE8=

jobs:
  include:
    - stage: Linters
      script: grunt lint
      install: pip install .[tools]

    - &unittests
      stage: Unit tests
      python: 3.6
      script: grunt tests:unit
      install: pip install .[tests]

    - <<: *unittests
      python: 3.7

    - <<: *unittests
      python: 3.8
      <<: *codacy_report
      <<: *codacy_secure

    - stage: Docs
      script: "grunt docs:build"
      install: pip install -r docs/requirements.txt
      <<: *install_pandoc

    - stage: Publish
      install: pip install .[tools]
      script: echo Deploying $(git describe --tags)
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        username: "__token__"
        <<: *pypi_secure
      "on":
          tags: true
          branch: master