language: python
python: 3.8

before_install:
  - nvm install 14
  - npm install
  - npm install -g grunt-cli

cache:
  - pip
  - npm

jobs:
  include:
    - stage: Linters
      script: grunt lint
      install: pip install .[tools]

    - &unittests
      stage: Unit tests
      python: 3.6
      script: grunt tests:unit
      install: pip install .[tests]

    - <<: *unittests
      python: 3.7

    - <<: *unittests
      python: 3.8

    - stage: Test coverage
      script: grunt tests:coverage
      install: pip install .[tests]
      before_script:
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

      after_success:
        - bash <(curl -Ls https://coverage.codacy.com/get.sh)

      env:
        secure: >-
          azswN6AXnY6C5WWuXK5z+v6zFbt5CLwY9Lbqt0w0kP4rxLPhnQB7iJQKvSacDiNt4DzGj
          /RHUYw6bO5pO7xb30ptzbBNd+W+fbMk4uLtzW24SEuVUSc7xDZbglXM8qvawmc/yA+bzp
          D6RrZHVwcb5/4efrllgHqah6WjShMaZzJVznVR+/eLfD+jU2R+52xK3mYYBCKsxdDZKi+
          oUY8lV0Zs1xdcalHMAqb3mKWZ8zb2dBnsLkc13fbTo4QYeV2j9YmVDtPUZ4L+cj/nCM1R
          SFt2gYoqshFMcplM2/+H+GreEpCrmbvi2mskZgl8hehIcr8w1jym3AcpCGRP9CvJ6Bazo
          6xvEw3OdrtAzw/z/k4aHnmjiqGphAJ6S69kKHrKcPddAx15Is6l9/uSxBxlMktAyv8KLO
          X1lUmOKx/IttdWjXQhzbZpvdiTAOTCbfzIggkws2kvCUjZ/HqE99/MUHt2QbWjSpqwB0n
          uM7bMm9RP1mHcIUAu6Drrq24fFtlx/f/hGIINHcE2gQJrRETVMOPqDJNxnhAIyEh4y69M
          3XtrqWZcNZ5vkQI0Rn6jwsyMaUkC2SuwBoolovWRpmi/bMl3QkL7hH9gq+1dNevJZVuSe
          P75buxwLaJqgfp0yaIxISoG0Yj5H0B9AqfZV/zai5QoMq8RVFIQinZ6N15JPb8=

    - stage: Docs
      script: "grunt docs:build"
      install: pip install -r docs/requirements.txt
      addons:
        apt:
          packages:
            - pandoc

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password:
    secure: >-
      JVlzD2HdIFVcp/9pHQFlpX8DlLE71c1VqEq4wbeJzK9UI+kqK0sTGhG8jqd2yNEuQIWf8hppb
      MY6WUCYAH7HY2wf1cjRPknWw/aB5zQB3+aFe4s0oEHNzkWRacBTyG/yENJEyh0QGWJxMcJ21x
      V1v5s5u4XuV1PHvCqJCl4MZ/1JD7CUWvrdmoHIsVng3Nyjjng8yfuwWaCvkewT/0lmlISF7EM
      Xhxu2j1YNnQRTs3SETjQkpovpdj67TJy/SNb8DJ8uV/2A6bQDxtd3C4YdpbkvvefTmLMfcbM2
      pGrpPi8P69Y0ts9H9i79c+OP1mNxOSpSbIWGGPHIuI1TSD5bddiGUDQpFuIZ5gQghoBGsJ5+S
      9suoMg0QyhF1wYFp0rlmgnMspBLJIO0nU3eRSjtilQQAc5mT9RmuB1y/iOFHnEUKgnFh4qE0Z
      zec3AyvphUzQI2IY9533e5Y07trXI9k5InGd4jWXpyaC1PJizToYCtOsjcJW7yZtEuZ8cPlR9
      XqROo4Edv7P1PWrqfGBtgQ1DA+3FCpn0BSb2SoNAZXLkZjicD82Bbc8INFabDkDIWW5Sn8EOH
      BO1/CA8f8eoa/qZFhUPodGz83vO02n7aBHuiR8nacV/JwS938feM4R95zT7hOwp3rqfVoTW0z
      MsaewpcVOnQr5MW3WqEeFXdXE8=
  "on":
    tags: true
